name: Docker Build to DockerHub

on:
  push:
    branches:
      - main
      - develop

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: packit/ap-it


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into Docker Hub
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: antoninjcb
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      - name: Build Docker image (latest)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker build ./ -t ${{ env.IMAGE_NAME }}:latest
      - name: Build Docker image (develop)
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          docker build ./ -t ${{ env.IMAGE_NAME }}:develop
    
      - name: Push Docker image (latest)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push ${{ env.IMAGE_NAME }}:latest
      - name: Push Docker image (develop)
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          docker push ${{ env.IMAGE_NAME }}:develop
